apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: customer-churn-predictor
  namespace: customer-churn
spec:
  predictor:
    serviceAccountName: customer-churn-sa
    model:
      modelFormat:
        name: sklearn
      storageUri: s3://churn-model-bucket-cicd-abhi/models/churn_model.pkl
  canaryTrafficPercent: 10
