resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - inference.yaml

images:
  - name: customer-churn-platform
    newName: customer-churn-platform
    newTag: latest
