apiVersion: v1
kind: Service
metadata:
  name: customer-churn-service
  namespace: customer-churn
spec:
  selector:
    app: customer-churn
    version: blue # Routes traffic to the active blue deployment. Can be updated to "green" for zero-downtime cutover.
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
