apiVersion: v1
kind: Service
metadata:
  name: customer-churn-service
  namespace: customer-churn
spec:
  selector:
    app: customer-churn
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
