global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'customer-churn-api'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['localhost:5000'] # Points to the local FastAPI app serving prometheus metrics
